### PR TITLE
WIP: Add macOS and Windows documentation build checks

### PR DESCRIPTION
**Pull request by tbirdso**

### CODE REVIEW

**Comment by tbirdso** [comment]
Build error in [CDash](https://open.cdash.org/viewBuildError.php?buildid=7102128):
> Error renaming from "/.../build/ITKDoxygenXML-TEMP/xml" to "/.../build/ITKDoxygenXML": No error

**Comment by thewtex** [comment]
@tbirdso could this please be rebased on `master` for updated CI?

**Comment by tbirdso** [comment]
CDash [build error](https://open.cdash.org/viewBuildError.php?buildid=7108658) in response to using GZip instead of BZip:
> CMake Error: Error processing file: /CMake/DownloadDoxygenXML.cmake

**Comment by tbirdso** [comment]
Observed no issue retrieving/decompressing archive on local Ubuntu machine, believe last issue was due to source tree name mismatch.

**Comment by tbirdso** [comment]
From most recent build:
> 2021-03-19T01:24:36.5330332Z [722/1581] Running gitstats
2021-03-19T01:24:36.5331365Z FAILED: CMakeFiles/gitstats 
2021-03-19T01:24:36.5333522Z cd /home/runner/work/bld && /home/runner/work/_temp/685782585/cmake-3.18.3-Linux-x86_64/bin/cmake -P /home/runner/work/bld/Utilities/SphinxExtensions/RunGitStats.cmake
2021-03-19T01:24:36.5335338Z CMake Error at Utilities/SphinxExtensions/RunGitStats.cmake:20 (message):
2021-03-19T01:24:36.5336109Z   Error running gitstats:
2021-03-19T01:24:36.5336421Z 
2021-03-19T01:24:36.5336683Z 
2021-03-19T01:24:36.9404374Z [723/1581] Building CXX object src/Core/Common/DuplicateAnImage/CMakeFiles/DuplicateAnImage.dir/Code.cxx.o
2021-03-19T01:24:49.0796628Z [724/1581] Building CXX object src/Filtering/LabelMap/ShapeAttributesForBinaryImage/CMakeFiles/ShapeAttributesForBinaryImage.dir/Code.cxx.o

**Pull request closed without merging**
