### PR TITLE
ENH: Fix macOS GHA toolchain

### PR DESCRIPTION
**Pull request by jhlegarreta**
- ENH: Use specific XCode version for GHA macOS 13 build
- ENH: Bump macOS version for notebook build, test GHA action step
- ENH: Bump checkout and setup-python GitHub actions versions
- ENH: Bump super-linter GitHub action version

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@thewtex Did not change these:
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pull/430/files#diff-eb9ae47cbd14fc8f82fa1280f41ef6b02f7e2e55165025ccad169dba48e750c9L133
https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pull/430/files#diff-eb9ae47cbd14fc8f82fa1280f41ef6b02f7e2e55165025ccad169dba48e750c9L143

following this:
https://github.com/InsightSoftwareConsortium/ITKRemoteModuleBuildTestPackageAction/pull/94#issuecomment-2420509961

Let me know if is unrelated and it should be changed.

**Comment by jhlegarreta** [comment]
`build-test-documentation` (ubuntu-22.04) has been failing consistently lately, so unrelated to this PR.

**Comment by jhlegarreta** [comment]
I can revert that Matt. Any suggestion how to solve the below when undoing the XCode pin?
```
ld: warning: ignoring duplicate libraries: '-lm'
```

**Comment by thewtex** [comment]
@jhlegarreta no-need to revert, thanks.

I think that warning has was addressed in a patch I made to ITK if I recall correctly.

**Pull request merged**
