### PR TITLE
ENH: Adding Python example to create mesh and cells

### PR DESCRIPTION
**Pull request by PranjalSahu**

### CODE REVIEW

**Comment by PranjalSahu** [comment]
https://examples.itk.org/src/core/mesh/addpointsandedges/documentation

**Review by thewtex — CHANGES_REQUESTED** [review]
@PranjalSahu awesome, thanks!

Please run [`black`](https://pypi.org/project/black/) on the code to fix the linting issues.

**Comment by PranjalSahu** [comment]
I will do it now.

**Comment by PranjalSahu** [comment]
Added license also.

**Review by dzenanz — APPROVED** [review]
Can we revisit #66 now?

**Comment by PranjalSahu** [comment]
@dzenanz I can complete that PR quickly.

**Pull request merged**
