### PR TITLE
BUG: Revert deploy to Netlify

### PR DESCRIPTION
**Pull request by tbirdso**
Partially addresses #341.

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
:book: :old_key:

**Comment by tbirdso** [comment]
I have opened #349 to track the two new test failures in CDash. Failures are unrelated to this change and likely result from a recent-ish change in wrapping for a certain ITK class.

**Comment by tbirdso** [comment]
Bumped ITK version to include resolution for #349 in [https://github.com/InsightSoftwareConsortium/ITK/pull/3406](https://github.com/InsightSoftwareConsortium/ITK/pull/3406)

**Comment by tbirdso** [comment]
Looks like auto-deploy is working, `examples.itk.org` is updated with today's date.

[https://examples.itk.org/](https://examples.itk.org/)

**Pull request merged**
