### PR TITLE
Correct output from distance calculation

### PR DESCRIPTION
**Pull request by melrobin**
Updated documentation to match Code.cxx.

### CODE REVIEW

**Review by dzenanz — COMMENTED** [review]
Was update of `breathelink` intentional? If so, please make it a new PR or at least a separate commit.

**Comment by melrobin** [comment]
I did not intend to update breathe, but it did show up as a submodule that needed to be updated.  I'll try to fix this.  I only intended to change the output.

**Comment by melrobin** [comment]
OK, I have updated the PR to undo my error.

**Comment by dzenanz** [comment]
Can you please squash the commits? Or just rebase the last one on top of master?

**Comment by melrobin** [comment]
Will restart.

**Pull request closed without merging**
