### PR TITLE
BUG: Move CI build-test-cxx source tree to path with shorter name

### PR DESCRIPTION
**Pull request by tbirdso**

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
LGTM, but I think it will conflict with the big rename PR.

**Comment by tbirdso** [comment]
This seeks to resolve the build issue seen in the rename PR:
> CMake Error at CMakeLists.txt:65 (message):
  The source directory is currently too long, 40 characters.  Please move the
  Examples source directory to a shorter path.

Is it reasonable to rebase that PR following this merge, if checks are successful?

**Comment by dzenanz** [comment]
> reasonable to rebase that PR following this merge

Yes!

**Comment by tbirdso** [comment]
Observed successful `build-test-cxx`. Splitting documentation changes into separate PR.

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]

**Pull request merged**
