### PR TITLE
ENH: Bump ITK to 5.4 Release Candidate 2

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Review by tbirdso — APPROVED** [review]
Great!

**Review by jhlegarreta — APPROVED** [review]
I'm missing a commit message body.

**Comment by thewtex** [comment]
The failing test, `ConvertImageWithLabelsToShapeLabelMapTest`, crashes on Windows sometimes in CI:

https://open.cdash.org/viewTest.php?onlyfailed&buildid=9080086
https://open.cdash.org/viewTest.php?onlyfailed&buildid=9079561

but it also passed:

https://open.cdash.org/viewTest.php?onlydelta&buildid=9079599

and it always passed on repeated runs locally.

However, the output of the test locally and CI is not correct, `16 objects` or `10 objects` when it should be `2 objects`. I am performing a bisect on this. 


I see `ConvertImageToLabelMapTest` also failed once on Windows:

  https://open.cdash.org/viewTest.php?onlyfailed&buildid=9079572

**Comment by thewtex** [comment]
> I'm missing a commit message body.

@jhlegarreta fixed :-)

**Comment by thewtex** [comment]
After spending some time investigating the failing test, I am punting with #420, so the rest of ITK 5.4 RC 2 is not delayed further.

**Pull request merged**
