### PR TITLE
Use pydata-sphinx-theme

### LINKED ISSUE #323: Use pydata-sphinx-theme
https://pydata-sphinx-theme.readthedocs.io/en/latest/index.html

### LINKED ISSUE #377: Bug: PDF and EPUB links broken
The download links for PDF and EPUB are 404s:
https://examples.itk.org/documentation/download/

PDF?  Gross.  Remove these links?

### PR DESCRIPTION
**Pull request by PaulHax**
New skin:
image

closes #323
closes #377

### CODE REVIEW

**Comment by tbirdso** [comment]
@PaulHax The new skin looks great!! There is one [docs build failure on CDash](https://open.cdash.org/viewBuildError.php?type=1&buildid=7926342), it looks like `DownloadExampleHighlighted.png` is downloaded in `Documentation/Build` but referenced in both `Documentation/Build` and `Documentation/Download`. Maybe the resource should be downloaded in both folders?

> 2022-05-20T23:00:23.4712844Z /home/runner/work/bld/ITKEx-build/Documentation/Download/index.rst:22: WARNING: image file not readable: Documentation/Download/DownloadExampleHighlighted.png

**Comment by tbirdso** [comment]
`build-test-cxx` failure looks like an issue fetching from `data.kitware.com` and will likely be resolved on re-run. Will let CI continue for now to get results from `build-test-documentation.

**Review by tbirdso — APPROVED** [review]
Awesome work @PaulHax ! CI is green 🟢 

Is this ready to be merged?

**Comment by PaulHax** [comment]
Good to go!  Thanks for the guidance.

**Pull request merged**
