### PR TITLE
DOC: Update build instructions for example .zip files

### PR DESCRIPTION
**Pull request by thewtex**
We just supply example .zip files now.

### CODE REVIEW

**Review by jhlegarreta — APPROVED** [review]
Is the change to the sha512 file intentional within this commit/PR?

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
> Is the change to the sha512 file intentional within this commit/PR?

The screenshot was probably updated 😄

**Comment by jhlegarreta** [comment]
> The screenshot was probably updated :smile:

Thanks @dzenanz :smiley: ; I did not pay attention to the filename :facepalm: .

**Comment by thewtex** [comment]
Yes, it was intentional :-) 💻

**Pull request merged**
